[Service]
Environment=LD_LIBRARY_PATH=/opt/t3-mesa-pvr-24.0.5/lib/aarch64-linux-gnu
Environment=LIBGL_DRIVERS_PATH=/opt/t3-mesa-pvr-24.0.5/lib/aarch64-linux-gnu/dri
Environment=GBM_BACKENDS_PATH=/opt/t3-mesa-pvr-24.0.5/lib/aarch64-linux-gnu/gbm
Environment=__EGL_VENDOR_LIBRARY_FILENAMES=/opt/t3-mesa-pvr-24.0.5/share/glvnd/egl_vendor.d/50_t3_mesa_2405.json
Environment=MESA_LOADER_DRIVER_OVERRIDE=pvr
Environment=KWIN_COMPOSE=O2ES
